version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      root-development-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /cloud
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      cloud-production-dependencies:
        dependency-type: production
      cloud-development-dependencies:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies
