export const PUBLIC_UI_COPY = {
  zh: {
    nav: {
      product: "AaaS",
      useAgent: "打开 Agent",
      switchLanguage: "Switch to English",
      skipToContent: "跳到主要内容",
    },
    home: {
      eyebrow: "AGENT AS A SERVICE",
      title: "不用重新交代。直接推进工作。",
      description:
        "粘贴别人分享的 Agent ID，直接说要完成什么。背景、关键判断和做事方式，它都已经了解。",
      agentIdLabel: "输入 Agent ID",
      agentIdHelper: "以 agt_ 开头",
      agentIdPlaceholder: "agt_...",
      openAgent: "开始使用",
      openingAgent: "正在打开…",
      missingId: "收到的是分享链接？直接打开，不用输入 ID。",
      storyEyebrow: "WHY IT MATTERS",
      storyTitle: "好的协作，不该换个人就从头开始。",
      closingTitle: "贴上 Agent ID，继续把事情做完。",
      closingBody: "它带着已有背景开始。你只需要说清楚下一步要什么。",
      publisherCta: "已经有一段成熟对话？把它发布成 Agent",
    },
    story: [
      {
        number: "01",
        title: "从已经完成的工作开始。",
        body:
          "它带着原会话里积累的背景、判断标准和做事方式。你的第一句话，就可以是真正要完成的任务。",
        action: "第一句话，就是真正的任务",
        cards: ["目标和约束", "已有背景", "表达与判断偏好", "验证过的方法"],
      },
      {
        number: "02",
        title: "交给对方一个 Agent，不是另一份说明。",
        body:
          "发出一个链接，对方就能在网页、Codex 或 Claude Code 里继续。少一次背景交接，多一点真正推进。",
        action: "少一次交接，多一点推进",
        destinations: ["网页", "Codex", "Claude Code"],
      },
      {
        number: "03",
        title: "共享同一种能力，保留各自的对话。",
        body:
          "每个人都能独立追问、修改和完成任务。你的内容只属于你，发布者和其他人的对话都保持原样。",
        action: "你的对话，只属于你",
        conversations: ["我的推进", "同事的推进"],
      },
    ],
    share: {
      eyebrow: "这个 Agent 已准备好",
      agentIdLabel: "Agent ID",
      copyAgentId: "复制 Agent ID",
      copied: "已复制",
      online: "在线，可以开始",
      offline: "当前暂不可用",
      descriptionFallback:
        "它已经了解此前的背景和做事方式。直接告诉它这次要完成什么。",
      promptLabel: "这次想让它帮你完成什么？",
      promptHelper: "直接说结果，不必重复背景。",
      promptPlaceholder: "例如：把这个方案收敛成三步，并指出最大风险…",
      send: "发送",
      newConversation: "新建对话",
      emptyTitle: "直接说你要的结果",
      emptyBody: "可以让它做决策、写草稿、分析问题，或给出下一步方案。",
      privateNote: "这段对话只属于你",
      useElsewhere: "也可以在 Codex 或 Claude Code 里继续",
      useElsewhereBody: "复制这个页面链接，粘贴给你的编码 Agent。它会读到安装与调用说明。",
      setupDetails: "查看使用方法",
      switchAgent: "打开另一个 Agent",
      loading: "正在读取 Agent…",
      notStarted: "等待你的第一个任务",
      cancel: "取消",
      cancelled: "本次调用已取消。",
      cancelFailed: "取消失败",
      callFailed: "调用失败",
    },
  },
  en: {
    nav: {
      product: "AaaS",
      useAgent: "Open an Agent",
      switchLanguage: "切换到中文",
      skipToContent: "Skip to main content",
    },
    home: {
      eyebrow: "AGENT AS A SERVICE",
      title: "Skip the briefing. Start the work.",
      description:
        "Paste the Agent ID someone shared with you and go straight to the task. The context, key decisions, and way of working are already there.",
      agentIdLabel: "Enter Agent ID",
      agentIdHelper: "Starts with agt_",
      agentIdPlaceholder: "agt_...",
      openAgent: "Start working",
      openingAgent: "Opening…",
      missingId: "Got a share link? Open it directly—no ID entry needed.",
      storyEyebrow: "WHY IT MATTERS",
      storyTitle: "Great work should not restart with every handoff.",
      closingTitle: "Paste the Agent ID. Keep the work moving.",
      closingBody: "It starts with the background. You start with what needs to happen next.",
      publisherCta: "Already have a great working session? Publish it as an Agent",
    },
    story: [
      {
        number: "01",
        title: "Start from work already done.",
        body:
          "It carries the context, judgment calls, and working style built in the original session. Your first message can be the real task.",
        action: "Begin with the outcome",
        cards: ["Goals and constraints", "Existing context", "How you decide", "Proven methods"],
      },
      {
        number: "02",
        title: "Hand over an Agent, not another brief.",
        body:
          "Send one link and the other person can continue on the web, in Codex, or in Claude Code. Less context transfer. More momentum.",
        action: "Less handoff. More momentum.",
        destinations: ["Web", "Codex", "Claude Code"],
      },
      {
        number: "03",
        title: "Share the capability. Keep every conversation private.",
        body:
          "Everyone can question, revise, and finish the work independently. Your content stays yours; the publisher’s original and everyone else’s conversations remain unchanged.",
        action: "Your conversation stays yours",
        conversations: ["My progress", "Teammate’s progress"],
      },
    ],
    share: {
      eyebrow: "THIS AGENT IS READY",
      agentIdLabel: "Agent ID",
      copyAgentId: "Copy Agent ID",
      copied: "Copied",
      online: "Online — ready to start",
      offline: "Unavailable right now",
      descriptionFallback:
        "It already knows the background and way of working. Tell it what needs to be finished.",
      promptLabel: "What should this Agent help you finish?",
      promptHelper: "Start with the outcome. No need to repeat the backstory.",
      promptPlaceholder: "For example: turn this plan into three steps and flag the biggest risk…",
      send: "Send",
      newConversation: "New conversation",
      emptyTitle: "Start with the result you need",
      emptyBody:
        "Ask for a decision, a draft, an analysis, or a concrete next-step plan.",
      privateNote: "Private to this conversation",
      useElsewhere: "Continue in Codex or Claude Code",
      useElsewhereBody:
        "Copy this page link and paste it into your coding Agent. It can read the setup and usage instructions.",
      setupDetails: "See how to use it",
      switchAgent: "Open another Agent",
      loading: "Loading Agent…",
      notStarted: "Waiting for your first task",
      cancel: "Cancel",
      cancelled: "This run was cancelled.",
      cancelFailed: "Cancellation failed",
      callFailed: "Call failed",
    },
  },
};
